#nullable enable

using System;

// ReSharper disable once CheckNamespace
namespace Aspid.Core.HSM
{
    /// <summary>
    /// Declares a state's parent in the hierarchy. <see cref="StateFactory"/> walks
    /// <see cref="ParentState"/> chains to build the full root-to-leaf state path.
    /// </summary>
    public interface IChildState
    {
        /// <summary>
        /// The parent state type. Must implement <see cref="IState"/>.
        /// </summary>
        public Type ParentState { get; }
    }

    /// <summary>
    /// Strongly-typed variant of <see cref="IChildState"/> that provides a compile-time parent reference.
    /// Typically generated by the source generator from <c>[ParentState(typeof(T))]</c>.
    /// </summary>
    /// <typeparam name="T">The parent state type.</typeparam>
    public interface IChildState<T> : IChildState
        where T : IState
    {
        Type IChildState.ParentState => typeof(T);
    }
}
