<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>Aspid.Core.HSM.Generators.Sample</RootNamespace>
        <!--        Dont support version-->
        <!--        <UnityVersion>6000.3.0f1</UnityVersion>-->
        <UnityVersion>6000.0.64f1</UnityVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aspid.Core.HSM.Generators\Aspid.Core.HSM.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Extensions\StateExtensions.cs">
        <Link>Source\Extensions\StateExtensions.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Extensions\StateMachineExtensions.cs">
        <Link>Source\Extensions\StateMachineExtensions.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Generation\AsyncAttribute.cs">
        <Link>Source\Generation\AsyncAttribute.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Generation\ControllerGroupAttribute.cs">
        <Link>Source\Generation\ControllerGroupAttribute.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Generation\ParentStateAttribute.cs">
        <Link>Source\Generation\ParentStateAttribute.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Generation\ReverseExecuteAttribute.cs">
        <Link>Source\Generation\ReverseExecuteAttribute.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\IChildState.cs">
        <Link>Source\IChildState.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\IController.cs">
        <Link>Source\IController.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\IState.cs">
        <Link>Source\IState.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\IStateMachine.cs">
        <Link>Source\IStateMachine.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\EmptyState.cs">
        <Link>Source\EmptyState.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\StateFactory.cs">
        <Link>Source\StateFactory.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\IStateScope.cs">
        <Link>Source\IStateScope.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\ScopeLifetime.cs">
        <Link>Source\ScopeLifetime.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Generation\ScopeLifetimeAttribute.cs">
        <Link>Source\Generation\ScopeLifetimeAttribute.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\Controllers\IDisposableController.cs">
        <Link>Runtime\Controllers\IDisposableController.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\Controllers\IEnterController.cs">
        <Link>Runtime\Controllers\IEnterController.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\Controllers\IExitController.cs">
        <Link>Runtime\Controllers\IExitController.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\Controllers\IFixedUpdateController.cs">
        <Link>Runtime\Controllers\IFixedUpdateController.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\Controllers\ILateUpdateController.cs">
        <Link>Runtime\Controllers\ILateUpdateController.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\Controllers\IUpdateController.cs">
        <Link>Runtime\Controllers\IUpdateController.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\StateMachines\MonoStateMachine.cs">
        <Link>Runtime\StateMachines\MonoStateMachine.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\StateMachines\MonoStateMachineCore.cs">
        <Link>Runtime\StateMachines\MonoStateMachineCore.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\StateMachines\StateMachineBase.cs">
        <Link>Runtime\StateMachines\StateMachineBase.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\StateMachines\StateMachineBase.Async.cs">
        <Link>Runtime\StateMachines\StateMachineBase.Async.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\StateMachines\StateMachineBase.Transitions.cs">
        <Link>Runtime\StateMachines\StateMachineBase.Transitions.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\StateMachines\MonoStateMachine.Async.cs">
        <Link>Runtime\StateMachines\MonoStateMachine.Async.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\Controllers\IAsyncEnterController.cs">
        <Link>Runtime\Controllers\IAsyncEnterController.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\Controllers\IAsyncExitController.cs">
        <Link>Runtime\Controllers\IAsyncExitController.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\ITransition.cs">
        <Link>Source\ITransition.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Generation\AsyncModeAttribute.cs">
        <Link>Source\Generation\AsyncModeAttribute.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Generation\AsyncExecutionMode.cs">
        <Link>Source\Generation\AsyncExecutionMode.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Generation\AsyncOfAttribute.cs">
        <Link>Source\Generation\AsyncOfAttribute.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Generation\TransitionAttribute.cs">
        <Link>Source\Generation\TransitionAttribute.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\IExtensionState.cs">
        <Link>Source\IExtensionState.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Source\Generation\ExtensionForAttribute.cs">
        <Link>Source\Generation\ExtensionForAttribute.cs</Link>
      </Compile>
      <Compile Include="..\..\..\Aspid.Core.HSM\Assets\Plugins\Aspid\Core\HSM\Unity\Runtime\StateMachines\StateMachineBase.Extensions.cs">
        <Link>Runtime\StateMachines\StateMachineBase.Extensions.cs</Link>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Unity3D" Version="3.1.1" />
      <PackageReference Include="UniTask" Version="2.5.10" />
    </ItemGroup>

</Project>
